{{- range .Values.apps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  {{- range $key, $value := .configMap }}
  {{ $key }}: {{ $value | quote | nindent 4 }}
  {{- end }}
{{- end }}
